backend:
  name: git-gateway
  branch: main

media_folder: "public"
public_folder: "/public"

collections:
  - name: "products"
    label: "Products"
    files:
      - label: "Product"
        name: "products"
        file: "/index.njk"
        format: "frontmatter"

        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - {
                  label: "Features",
                  name: "features",
                  widget: "list",
                  fields:
                    [{ label: "Feature", name: "feature", widget: "string" }],
                }
              - {
                  label: "Rating",
                  name: "rating",
                  widget: "string",
                  default: "⭐⭐⭐⭐⭐",
                }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "WhatsApp Link", name: "whatsapp", widget: "string" }
